FROM python:3.12.6-alpine3.20

# Set the working directory
WORKDIR /app

# Some required Python dependencies, such as pymssql, have C extensions
# and require certain utilities be installed on Alpine Linux. This is
# necessary to ensure their Python wheels are properly built with pip.
RUN apk update && apk add --no-cache \
	gcc \	
	musl-dev \
	unixodbc-dev \
	freetds-dev \
	krb5-dev \
	libressl-dev

# Install dependencies
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN pip install pytest

# Copy all required files for the test environment
COPY ./src/ ./src/
COPY ./tests/ ./tests/
COPY ./.env ./.env

# Run Pytest
CMD ["pytest", "tests"]
