services:
  backend:
    build:
      context: ../..
      dockerfile: docker/images/Dockerfile.dev
    ports:
      - "8080:8080"
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
  flyway:
    container_name: flyway
    image: flyway/flyway
    command: ["-url=jdbc:sqlserver://mssql:1433;encrypt=true;trustServerCertificate=true", "-user=sa", "-password=${MSSQL_PASSWORD}", "-X", "migrate"]
    depends_on:
      - mssql
    volumes:
      - ../../src/db/mssql/migrations/:/flyway/sql
